version: 2.1
jobs:
  compile:
   docker:
      - image: fr3akyphantom/droid-builder:latest
   steps:
      - run:
          command: |
           git clone --depth=1 https://github.com/celtare21/android_kernel_realme_sm6150 --single-branch -b r11staging mido
           cd mido
           wget https://raw.githubusercontent.com/shashank1436/ci/staging/build.sh
           bash build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
